### ISSUE TITLE
? What's the project name (this will also be your namespace name)? removes dots

### ISSUE THREAD

**Issue by hunterconcepts** [rahulsahay19/generator-aspnetcore-angular-2#2]
If you add a dot into the namespace it gets removed

Test.Web

becomes

TestWeb

**Comment by rahulsahay19** [comment]
Hi,

This is not because of my generator. This is the behavior of NPM packages via yeoman. They don't support dot operator as in project namespace by default. Hence, if you give . there, it will be truncated. You can try other asp.net core generators as well. There also its the same case.

Thanks,
Rahul
